name = "slack-tweet-command"
type = "javascript"
account_id = ""
workers_dev = true

# see https://github.com/cloudflare/wrangler/releases/tag/v1.15.0-custom-builds-rc.2
[build]
upload_format = "service-worker"
command = "yarn && yarn build"
